### ISSUE TITLE
Error after account was funded

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-create-account#28]
i get this error
<img width="566" alt="Screenshot 2022-08-24 at 14 36 02" src="https://user-images.githubusercontent.com/1674145/186445457-1db22a05-5aa7-4027-a717-6731fbf4d0f4.png">
i shared account details on telegram 
even if you go back and import account it still does not go through

**Comment by molekilla** [comment]
@tfius @tomicvladan 

We need to change the code to have a backend either Go or NodeJS, where the `registerUser` is done async.


- Need to fire and forget this to a REST call

```typescript

const WaitingPayment = ({
  account,
  onPaymentDetected,
  onError,
}: WaitingPaymentProps) => {
  const timer = useRef<NodeJS.Timeout | null>();

  const checkPayment = async () => {
    try {
      const balance = await getAccountBalance(account);

      if (balance.gt(0)) {
        closeTimer();
        onPaymentDetected();
      }
    } catch (error) {
      console.error(error);
      closeTimer();
      onError();
    }
  };

```

- Stored the pending approval or have chain ops script that polls the transaction every n seconds and
- A receiver that registers ENS. That's why there was this concept of "Controller", because this piece is done on backend.
```typescript

  const onPaymentConfirmed = () => {
    setStep(Steps.Loading);
    registerUser();
  };

  const onError = () => {
    setStep(Steps.Error);
  };

  const registerUser = async () => {
    try {
      const { username, password, privateKey, mnemonic } = data;

      let wallet;

      if (privateKey) {
        wallet = new Wallet(privateKey);
      } else if (mnemonic) {
        wallet = Wallet.fromMnemonic(mnemonic);
      } else {
        throw new Error(
          "Private key or mnemonic must be set in order to register account"
        );
      }

      fdpClient.account.setActiveAccount(wallet);

      await fdpClient.account.register(username, password);

      setStep(Steps.Complete);
    } catch (error) {
      console.error(error);
      setStep(Steps.Error);
    }
  };
```


The sequence of actions
Option # 1
- User encrypts mnemonic -> Uploads to FDP
- (required: a proof of privatekey/inclusion uploaded to smart contract / offchain storage)
- User sends funds to new address -> Chain ops listen for Transfer event
- (required: A backend service verifies transfer/payment matches proof of privatekey eg public key is indeed private key)
- register must be then execute on the client 

Option  # 2

- User sends funds to an address manage by a smart contract (RegisterController), with payload including username, address and amount
- Smart contract sends funds to address and at the same time register ENS name
- The only thing the smart contract will required additionally is an `estimateRegistrationCost`, which should calculate the cost of routing funds and registering ENS.

I like option 2 the most

**Comment by tfius** [comment]
I dont think there is any need for controller or backend, only timed function in 10s interval that checks the balance if user account (which is already know) once balance is there, ENS can be written to, then needs to wait for TX to succede and then FDP ens can be written. 
- it could fail at writing to ENS for numerous reasons
- it can fail writing to FDP for numerous reasons
so checks must be in place:
1. if ENS exists
- pubKey is same as users, then check FDP if written correctly
- pubKey not same, then probably from other user
2. if ENS does not exist
- must do all steps (ENS and FDP)
it can happen that user funds account and FDP part fails, this needs to be checked and needed actions to complete FDP account creation must be redone.

**Comment by molekilla** [comment]
I disagree,  eg ens register and  funds are not being gas estimated, user has no idea how much is required

**Comment by tomicvladan** [comment]
This error is caused by this bug: https://github.com/fairDataSociety/fdp-contracts/issues/88
